package com.gharbazaar.backend.enums;

public enum ErrorCode {
    NONE, CONFLICT, MISSING_TOKEN, INTERNAL_SERVER_ERROR,
    EXPIRED_JWT, LOCKED, DISABLED, UNAUTHORIZED, INVALID_PURPOSE,
    INVALID_SUBJECT, USER_NOT_FOUND, USED_TOKEN, FORBIDDEN,
    MALFORMED_JWT, NOT_FOUND, INVALID_REQUEST_BODY, MESSAGE_NOT_READEABLE, INVALID_JWT
}
